# Generated by Django 3.0.6 on 2020-09-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotorTest_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-version'], 'verbose_name': '上位机版本管理', 'verbose_name_plural': '上位机版本管理'},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='testLog',
            field=models.FileField(blank=True, upload_to='MotorTest/%Y/%m', verbose_name='电机测试记录log'),
        ),
    ]
