# Generated by Django 3.0.6 on 2020-09-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotorTest_project', '0002_auto_20200906_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='testId',
            field=models.CharField(default='0', max_length=255, unique=True, verbose_name='测试ID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='FunctionResult',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MotorTest_project.Function', verbose_name='电机功能测试表'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='motorMemory',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MotorTest_project.Memory', verbose_name='电机内存表'),
        ),
    ]
