# Generated by Django 3.0.6 on 2020-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotorTest_project', '0003_auto_20200906_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='testId',
            field=models.CharField(default='0', max_length=255, unique=True, verbose_name='测试ID'),
        ),
        migrations.AddField(
            model_name='memory',
            name='testId',
            field=models.CharField(default='0', max_length=255, unique=True, verbose_name='测试ID'),
        ),
    ]
