# Generated by Django 3.0.6 on 2020-07-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeOfProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection', models.CharField(max_length=32, unique=True, verbose_name='防护等级IP')),
            ],
            options={
                'verbose_name': '防护等级',
                'verbose_name_plural': '防护等级',
            },
        ),
        migrations.CreateModel(
            name='RatedCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(max_length=32, unique=True, verbose_name='额定电流A')),
            ],
            options={
                'verbose_name': '额定电流',
                'verbose_name_plural': '额定电流',
            },
        ),
        migrations.CreateModel(
            name='RatedPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=32, unique=True, verbose_name='额定功率W')),
            ],
            options={
                'verbose_name': '额定功率',
                'verbose_name_plural': '额定功率',
            },
        ),
        migrations.CreateModel(
            name='RatedSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=32, unique=True, verbose_name='额定转速Rpm')),
            ],
            options={
                'verbose_name': '额定转速',
                'verbose_name_plural': '额定转速',
            },
        ),
        migrations.CreateModel(
            name='RatedTorque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torque', models.CharField(max_length=32, unique=True, verbose_name='额定扭矩')),
            ],
            options={
                'verbose_name': '额定扭矩',
                'verbose_name_plural': '额定扭矩',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(default='', max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('cTime', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-cTime'],
            },
        ),
        migrations.CreateModel(
            name='MotorImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.ManyToManyField(to='web_project.RatedPower', verbose_name='电机测试图片')),
            ],
            options={
                'verbose_name': '电机测试图片',
                'verbose_name_plural': '电机测试图片',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='电机名称')),
                ('img', models.ImageField(upload_to='static/Motor/', verbose_name='电机图片')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_project.RatedCurrent')),
                ('protection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_project.DegreeOfProtection')),
                ('speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_project.RatedSpeed')),
                ('torque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_project.RatedTorque')),
            ],
            options={
                'verbose_name': '电机名称',
                'verbose_name_plural': '电机名称',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('cTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_project.User')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-cTime'],
            },
        ),
    ]
