# Generated by Django 3.0.6 on 2020-07-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorimg',
            name='power',
        ),
        migrations.AddField(
            model_name='motorimg',
            name='power',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='web_project.RatedPower'),
        ),
    ]
