# Generated by Django 3.0.6 on 2020-07-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0004_auto_20200707_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField(unique=True, verbose_name='工作电压')),
            ],
            options={
                'verbose_name': '工作电压',
                'verbose_name_plural': '工作电压',
            },
        ),
        migrations.AlterField(
            model_name='motorimg',
            name='img1',
            field=models.ImageField(default=True, upload_to='image/', verbose_name='电机图片1'),
        ),
        migrations.AlterField(
            model_name='motorimg',
            name='img2',
            field=models.ImageField(default=True, upload_to='image/', verbose_name='电机图片2'),
        ),
        migrations.AlterField(
            model_name='motorimg',
            name='img3',
            field=models.ImageField(default=True, upload_to='image/', verbose_name='电机图片3'),
        ),
        migrations.AddField(
            model_name='motor',
            name='voltage',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='web_project.Voltage'),
        ),
    ]
