# Generated by Django 3.0.6 on 2020-07-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0005_auto_20200709_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='voltage',
        ),
    ]
