# Generated by Django 3.0.6 on 2020-07-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0006_remove_motor_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='voltage',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='web_project.Voltage'),
        ),
    ]
