# Generated by Django 3.0.6 on 2020-07-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0007_motor_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='voltage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_project.Voltage'),
        ),
    ]
