# Generated by Django 3.0.6 on 2020-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0008_auto_20200709_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorimg',
            name='img1',
            field=models.ImageField(default=True, upload_to='image/%Y/%m', verbose_name='电机图片1'),
        ),
        migrations.AlterField(
            model_name='motorimg',
            name='img2',
            field=models.ImageField(default=True, upload_to='image/%Y/%m', verbose_name='电机图片2'),
        ),
        migrations.AlterField(
            model_name='motorimg',
            name='img3',
            field=models.ImageField(default=True, upload_to='image/%Y/%m', verbose_name='电机图片3'),
        ),
    ]
